-- Production seed: intentionally empty.
-- Create real users via Admin → Users (invite).
-- Upload real documents via Admin → Documents.
-- Create real projects via Admin → Projects.
--
-- Do not insert demo partners, demo projects, or demo library rows.
